[package]
name = "nprs"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = { version = "0.29.2", features = [ "rand" ] }
png = "0.17.13"
half = "2.4.1"
thiserror = "2.0.0"
voronoi = "0.1.4"
rand = "0.8.5"
radsort = "0.1.1"
